version: "3.7"

services:

  tma-cah:
    image: emcniece/dockeryourxyzzy:latest
    build:
      context: .
      dockerfile: ./docker-tma-cah/Dockerfile
    ports:
      - "6969:8080"
    volumes:
      - ./init-db.d:/docker-entrypoint-initdb.d  # Used to transfer `cah_cards.sql` from `tma-cah` container (where CustomCAH repo is cloned) into `postgres` container.
      - ./overrides:/overrides
    networks:
      - tma-cah-net
    environment:
      - TOMCAT_USER=${TOMCAT_USER}
      - TOMCAT_PASSWORD=${TOMCAT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  postgres:
    image: "postgres:alpine"
    build:
      context: .
      dockerfile: ./docker-postgres/Dockerfile
    volumes:
      # - ./data/pgdata:/var/lib/postgresql/data  # Persistent database storage
      - ./init-db.d:/docker-entrypoint-initdb.d   # Entrypoint scripts, run at build time
      - ./overrides:/overrides
    networks:
      - tma-cah-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  tma-cah-net:
